# Generated by Django 3.2.6 on 2021-10-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_game_game_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_img',
            field=models.CharField(default='https://www.food4fuel.com/wp-content/uploads/woocommerce-placeholder-600x600.png', max_length=500),
        ),
    ]
