# Generated by Django 3.2.6 on 2021-11-08 15:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_marks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='marks',
            new_name='mark',
        ),
    ]
